title: Mandar Angchekar's Portfolio
description: >-
  Welcome to my portfolio where I showcase my projects and skills in data analysis, machine learning, and software development.
email: mangchek@syr.edu
url: "https://mandarangchekar.github.io" # Customize with your actual GitHub Pages URL
twitter_username: mandarangchekar
github_username: mandarangchekar
linkedin_username: mandarangchekar
theme: jekyll-theme-minima 
