title: Mandar Angchekar's Portfolio
description: Welcome to my professional portfolio site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mandarangchekar
github_username:  mandarangchekar
linkedin_username: mandar-angchekar-4220641a7

theme: minima # Change this to your Jekyll theme, which should be responsive
