title: Mandar Angchekar's Portfolio
description: >-
  Welcome to my portfolio where I showcase my projects and skills in data analysis, machine learning, and software development.
email: your-email@example.com
url: "https://mandarangchekar.github.io" # Customize with your actual GitHub Pages URL
twitter_username: your-twitter # Optional
github_username: mandarangchekar
linkedin_username: your-linkedin # Optional
theme: minima # or another Jekyll theme you prefer
